#!/usr/bin/env python3
"""Export selected XIVAPI v2 rows as Lua data files.

This script is intentionally dependency-free. It runs outside SND, resolves and
validates game data through XIVAPI, then writes small Lua lookup tables that SND
can require without doing HTTP requests on the game thread.
"""

from __future__ import annotations

import argparse
import json
import sys
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any
from urllib.error import HTTPError, URLError
from urllib.parse import quote, urlencode
from urllib.request import Request, urlopen


BASE_URL = "https://v2.xivapi.com/api"
LANGUAGES = ("en", "de", "fr", "ja")
ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT_DIR = ROOT / "data" / "generated"
CACHE_FILENAME = "_xivapi_export_cache.json"


class ExportError(RuntimeError):
    pass


class MissingData(Exception):
    def __init__(self, status: str, message: str):
        super().__init__(message)
        self.status = status


def parse_id_spec(value: str) -> list[int]:
    """Parse comma-separated IDs and inclusive ranges like '1,5,50-80'."""
    ids: set[int] = set()
    if not value:
        return []

    for raw_part in value.split(","):
        part = raw_part.strip()
        if not part:
            continue

        if "-" in part:
            start_raw, end_raw = part.split("-", 1)
            start = int(start_raw.strip())
            end = int(end_raw.strip())
            if start > end:
                raise ExportError(f"Invalid range '{part}': start is greater than end")
            ids.update(range(start, end + 1))
        else:
            ids.add(int(part))

    return sorted(ids)


def lua_escape(value: Any) -> str:
    text = "" if value is None else str(value)
    return (
        text.replace("\\", "\\\\")
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        .replace('"', '\\"')
    )


def lua_value(value: Any, indent: int = 0) -> str:
    if value is None:
        return "nil"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, str):
        return f'"{lua_escape(value)}"'
    if isinstance(value, list):
        if not value:
            return "{}"
        spaces = " " * indent
        child = " " * (indent + 4)
        lines = ["{"]
        for item in value:
            lines.append(f"{child}{lua_value(item, indent + 4)},")
        lines.append(f"{spaces}}}")
        return "\n".join(lines)
    if isinstance(value, dict):
        if not value:
            return "{}"
        spaces = " " * indent
        child = " " * (indent + 4)
        lines = ["{"]
        if set(value).issubset(set(LANGUAGES)):
            items = [(key, value[key]) for key in LANGUAGES if key in value]
        else:
            items = list(value.items())
        for key, item in items:
            if isinstance(key, int):
                key_repr = f"[{key}]"
            elif isinstance(key, str) and key.isidentifier() and not key.startswith("__"):
                key_repr = key
            else:
                key_repr = f'["{lua_escape(key)}"]'
            lines.append(f"{child}{key_repr} = {lua_value(item, indent + 4)},")
        lines.append(f"{spaces}}}")
        return "\n".join(lines)
    return f'"{lua_escape(value)}"'


def write_lua_table(path: Path, rows: dict[int, dict[str, Any]], meta: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "-- ======================================================================",
        "-- Generated by tools/export_xivapi_data.py - do not edit manually.",
        "-- ======================================================================",
        "local data = {",
        f"    _meta = {lua_value(meta, 4)},",
    ]

    for row_id in sorted(rows):
        lines.append(f"    [{row_id}] = {lua_value(rows[row_id], 4)},")

    lines.extend(["}", "", "return data", ""])
    path.write_text("\n".join(lines), encoding="utf-8")


def load_cache(output_dir: Path) -> dict[str, dict[str, dict[str, Any]]]:
    path = output_dir / CACHE_FILENAME
    if not path.exists():
        return {}
    with path.open("r", encoding="utf-8") as handle:
        data = json.load(handle)
    return data if isinstance(data, dict) else {}


def save_cache(output_dir: Path, cache: dict[str, dict[str, dict[str, Any]]]) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    path = output_dir / CACHE_FILENAME
    path.write_text(
        json.dumps(cache, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )


def missing_cache(cache: dict[str, Any]) -> dict[str, dict[str, dict[str, Any]]]:
    missing = cache.setdefault("_missing", {})
    if not isinstance(missing, dict):
        cache["_missing"] = {}
        missing = cache["_missing"]
    return missing


def get_missing(cache: dict[str, Any], type_name: str, row_id: int) -> dict[str, Any] | None:
    type_missing = missing_cache(cache).get(type_name, {})
    if not isinstance(type_missing, dict):
        return None
    entry = type_missing.get(str(row_id))
    return entry if isinstance(entry, dict) else None


def set_missing(cache: dict[str, Any], type_name: str, row_id: int, status: str, message: str) -> None:
    missing = missing_cache(cache)
    type_missing = missing.setdefault(type_name, {})
    type_missing[str(row_id)] = {
        "id": row_id,
        "status": status,
        "message": message,
        "last_checked_at": datetime.now(timezone.utc).replace(microsecond=0).isoformat(),
    }


def clear_missing(cache: dict[str, Any], type_name: str, row_id: int) -> None:
    missing = missing_cache(cache)
    type_missing = missing.get(type_name)
    if isinstance(type_missing, dict):
        type_missing.pop(str(row_id), None)
        if not type_missing:
            missing.pop(type_name, None)


def missing_ids(cache: dict[str, Any], type_name: str | None = None) -> dict[str, list[int]]:
    missing = missing_cache(cache)
    type_names = [type_name] if type_name else sorted(k for k in missing if k in EXPORTERS)
    out: dict[str, list[int]] = {}
    for current_type in type_names:
        type_missing = missing.get(current_type, {})
        if isinstance(type_missing, dict):
            ids = sorted(int(row_id) for row_id in type_missing if str(row_id).isdigit())
            if ids:
                out[current_type] = ids
    return out


def http_json(path: str, params: dict[str, Any] | None = None, retries: int = 2) -> dict[str, Any] | None:
    url = f"{BASE_URL}{path}"
    if params:
        url = f"{url}?{urlencode(params, safe=',.~()@[]')}"

    for attempt in range(retries + 1):
        try:
            request = Request(url, headers={"User-Agent": "snd-xivapi-exporter/1.0"})
            with urlopen(request, timeout=30) as response:
                return json.loads(response.read().decode("utf-8"))
        except HTTPError as exc:
            if exc.code == 404:
                raise MissingData("not_found", f"HTTP 404 for {url}") from exc
            if attempt >= retries:
                raise ExportError(f"HTTP {exc.code} for {url}") from exc
        except (URLError, TimeoutError, json.JSONDecodeError) as exc:
            if attempt >= retries:
                raise ExportError(f"Request failed for {url}: {exc}") from exc
        time.sleep(0.4 * (attempt + 1))

    return None


def lang_fields(field: str) -> str:
    return ",".join(f"{field}@lang({lang})" for lang in LANGUAGES)


def nested_lang_fields(prefix: str, field: str) -> str:
    return ",".join(f"{prefix}.{field}@lang({lang})" for lang in LANGUAGES)


def extract_langs(fields: dict[str, Any], field: str) -> dict[str, str]:
    return {lang: fields.get(f"{field}@lang({lang})") or "" for lang in LANGUAGES}


def ref_id(value: Any) -> int | None:
    if isinstance(value, dict):
        row_id = value.get("row_id") or value.get("value")
        return int(row_id) if isinstance(row_id, int) else None
    if isinstance(value, int):
        return value
    return None


def field_id(fields: dict[str, Any], name: str) -> int:
    return ref_id(fields.get(f"{name}@as(raw)")) or ref_id(fields.get(name)) or 0


def fetch_sheet_row(sheet: str, row_id: int, fields: str) -> dict[str, Any] | None:
    encoded_sheet = quote(sheet, safe="")
    return http_json(f"/sheet/{encoded_sheet}/{row_id}", {"fields": fields})


def row_fields(row: dict[str, Any] | None, sheet: str, row_id: int) -> dict[str, Any]:
    fields = row.get("fields") if isinstance(row, dict) else None
    if not isinstance(fields, dict) or not fields:
        raise MissingData("empty", f"{sheet}/{row_id} returned empty fields")
    return fields


def fetch_item(row_id: int) -> dict[str, Any] | None:
    row = fetch_sheet_row("Item", row_id, lang_fields("Name"))
    fields = row_fields(row, "Item", row_id)
    names = extract_langs(fields, "Name")
    if not any(names.values()):
        raise MissingData("empty", f"Item/{row_id} has no localized Name")
    return {"id": row_id, "name": names}


def fetch_bnpc_name(row_id: int) -> dict[str, Any] | None:
    fields_query = f"{lang_fields('Singular')},{lang_fields('Plural')}"
    row = fetch_sheet_row("BNpcName", row_id, fields_query)
    fields = row_fields(row, "BNpcName", row_id)
    singular = extract_langs(fields, "Singular")
    if not any(singular.values()):
        raise MissingData("empty", f"BNpcName/{row_id} has no localized Singular")
    return {
        "id": row_id,
        "singular": singular,
        "plural": extract_langs(fields, "Plural"),
    }


def fetch_place_name(row_id: int) -> dict[str, Any] | None:
    row = fetch_sheet_row("PlaceName", row_id, lang_fields("Name"))
    fields = row_fields(row, "PlaceName", row_id)
    names = extract_langs(fields, "Name")
    if not any(names.values()):
        raise MissingData("empty", f"PlaceName/{row_id} has no localized Name")
    return {"id": row_id, "name": names}


def nested_langs(fields: dict[str, Any], ref_field: str, name_field: str = "Name") -> dict[str, str]:
    ref = fields.get(ref_field)
    if not isinstance(ref, dict):
        return {lang: "" for lang in LANGUAGES}
    nested_fields = ref.get("fields") or {}
    return extract_langs(nested_fields, name_field)


def fetch_territory(row_id: int) -> dict[str, Any] | None:
    fields_query = ",".join(
        [
            "Name",
            "Map@as(raw)",
            "PlaceName@as(raw)",
            "PlaceNameRegion@as(raw)",
            "PlaceNameZone@as(raw)",
            nested_lang_fields("PlaceName", "Name"),
            nested_lang_fields("PlaceNameRegion", "Name"),
            nested_lang_fields("PlaceNameZone", "Name"),
        ]
    )
    row = fetch_sheet_row("TerritoryType", row_id, fields_query)
    fields = row_fields(row, "TerritoryType", row_id)

    names = nested_langs(fields, "PlaceName")
    if not any(names.values()):
        raise MissingData("empty", f"TerritoryType/{row_id} has no localized PlaceName")

    result = {
        "id": row_id,
        "internal_name": fields.get("Name") or "",
        "name": names,
        "place_name_id": field_id(fields, "PlaceName"),
        "region_place_name_id": field_id(fields, "PlaceNameRegion"),
        "zone_place_name_id": field_id(fields, "PlaceNameZone"),
        "map_id": field_id(fields, "Map"),
        "region_name": nested_langs(fields, "PlaceNameRegion"),
        "zone_name": nested_langs(fields, "PlaceNameZone"),
    }
    return result


def fetch_map(row_id: int) -> dict[str, Any] | None:
    fields_query = ",".join(
        [
            "Id",
            "SizeFactor",
            "OffsetX",
            "OffsetY",
            "TerritoryType@as(raw)",
            "PlaceName@as(raw)",
            "PlaceNameRegion@as(raw)",
            "PlaceNameSub@as(raw)",
            nested_lang_fields("PlaceName", "Name"),
            nested_lang_fields("PlaceNameRegion", "Name"),
            nested_lang_fields("PlaceNameSub", "Name"),
        ]
    )
    row = fetch_sheet_row("Map", row_id, fields_query)
    fields = row_fields(row, "Map", row_id)

    names = nested_langs(fields, "PlaceName")
    if not any(names.values()):
        raise MissingData("empty", f"Map/{row_id} has no localized PlaceName")

    return {
        "id": row_id,
        "map_id": fields.get("Id") or "",
        "name": names,
        "territory_id": field_id(fields, "TerritoryType"),
        "place_name_id": field_id(fields, "PlaceName"),
        "region_place_name_id": field_id(fields, "PlaceNameRegion"),
        "sub_place_name_id": field_id(fields, "PlaceNameSub"),
        "region_name": nested_langs(fields, "PlaceNameRegion"),
        "sub_name": nested_langs(fields, "PlaceNameSub"),
        "size_factor": fields.get("SizeFactor") or 0,
        "offset_x": fields.get("OffsetX") or 0,
        "offset_y": fields.get("OffsetY") or 0,
    }


def fetch_bnpc_base(row_id: int) -> dict[str, Any] | None:
    fields_query = ",".join(
        [
            "BNpcCustomize@as(raw)",
            "BNpcParts@as(raw)",
            "Battalion@as(raw)",
            "Behavior@as(raw)",
            "ModelChara@as(raw)",
            "NpcEquip@as(raw)",
            "Rank",
            "Scale",
            "IsTargetLine",
            "IsDisplayLevel",
            "IsOmnidirectional",
        ]
    )
    row = fetch_sheet_row("BNpcBase", row_id, fields_query)
    fields = row_fields(row, "BNpcBase", row_id)
    return {
        "id": row_id,
        "bnpc_customize_id": field_id(fields, "BNpcCustomize"),
        "bnpc_parts_id": field_id(fields, "BNpcParts"),
        "battalion_id": field_id(fields, "Battalion"),
        "behavior_id": field_id(fields, "Behavior"),
        "model_chara_id": field_id(fields, "ModelChara"),
        "npc_equip_id": field_id(fields, "NpcEquip"),
        "rank": fields.get("Rank") or 0,
        "scale": fields.get("Scale") or 0,
        "is_target_line": fields.get("IsTargetLine") == True,
        "is_display_level": fields.get("IsDisplayLevel") == True,
        "is_omnidirectional": fields.get("IsOmnidirectional") == True,
    }


EXPORTERS = {
    "items": {
        "filename": "items.lua",
        "sheet": "Item",
        "fetch": fetch_item,
        "search_field": "Name",
        "search_fields": "Name",
    },
    "bnpc_names": {
        "filename": "bnpc_names.lua",
        "sheet": "BNpcName",
        "fetch": fetch_bnpc_name,
        "search_field": "Singular",
        "search_fields": "Singular",
    },
    "territories": {
        "filename": "territories.lua",
        "sheet": "TerritoryType",
        "fetch": fetch_territory,
        "search_field": "PlaceName.Name",
        "search_fields": "PlaceName.Name,Map@as(raw)",
    },
    "maps": {
        "filename": "maps.lua",
        "sheet": "Map",
        "fetch": fetch_map,
        "search_field": "PlaceName.Name",
        "search_fields": "PlaceName.Name,TerritoryType@as(raw)",
    },
    "place_names": {
        "filename": "place_names.lua",
        "sheet": "PlaceName",
        "fetch": fetch_place_name,
        "search_field": "Name",
        "search_fields": "Name",
    },
    "bnpc_bases": {
        "filename": "bnpc_bases.lua",
        "sheet": "BNpcBase",
        "fetch": fetch_bnpc_base,
        "search_field": "Rank",
        "search_fields": "Rank,Scale,ModelChara@as(raw)",
    },
}

SEARCHABLE_TYPES = {"items", "bnpc_names", "territories", "maps", "place_names"}


ALIASES = {
    "item": "items",
    "items": "items",
    "mob": "bnpc_names",
    "mobs": "bnpc_names",
    "monster": "bnpc_names",
    "monsters": "bnpc_names",
    "bnpc_name": "bnpc_names",
    "bnpc_names": "bnpc_names",
    "territory": "territories",
    "territories": "territories",
    "zone": "territories",
    "zones": "territories",
    "map": "maps",
    "maps": "maps",
    "place": "place_names",
    "place_name": "place_names",
    "place_names": "place_names",
    "bnpc_base": "bnpc_bases",
    "bnpc_bases": "bnpc_bases",
}


def normalize_type(value: str) -> str:
    key = value.strip().lower().replace("-", "_")
    if key not in ALIASES:
        valid = ", ".join(sorted(set(ALIASES)))
        raise ExportError(f"Unknown type '{value}'. Valid aliases: {valid}")
    return ALIASES[key]


def parse_types(value: str) -> list[str]:
    seen: set[str] = set()
    out: list[str] = []
    for part in value.split(","):
        if not part.strip():
            continue
        normalized = normalize_type(part)
        if normalized not in seen:
            out.append(normalized)
            seen.add(normalized)
    return out


def export_type(
    type_name: str,
    ids: list[int],
    output_dir: Path,
    cache: dict[str, Any],
    replace: bool,
    refresh: bool,
    retry_missing: bool,
) -> None:
    config = EXPORTERS[type_name]
    target = output_dir / config["filename"]
    if target.exists() and type_name not in cache and not replace:
        raise ExportError(
            f"{target} exists, but {CACHE_FILENAME} has no cached rows for {type_name}. "
            "Run again with --replace to rebuild this file."
        )
    cached_rows = {} if replace else cache.get(type_name, {})
    if not isinstance(cached_rows, dict):
        cached_rows = {}
    rows: dict[int, dict[str, Any]] = {int(row_id): row for row_id, row in cached_rows.items()}
    not_found: list[int] = []
    empty: list[int] = []
    skipped: list[int] = []
    skipped_missing: list[int] = []

    fetcher = config["fetch"]
    print(f"Exporting {type_name}: {len(ids)} requested IDs")
    for index, row_id in enumerate(ids, start=1):
        if row_id in rows and not replace and not refresh:
            clear_missing(cache, type_name, row_id)
            skipped.append(row_id)
            print(f"  [{index}/{len(ids)}] {type_name} ID {row_id} already cached - skipped")
            continue

        missing_entry = get_missing(cache, type_name, row_id)
        if missing_entry and not replace and not refresh and not retry_missing:
            skipped_missing.append(row_id)
            status = missing_entry.get("status", "missing")
            print(f"  [{index}/{len(ids)}] {type_name} ID {row_id} known {status} - skipped")
            continue

        print(f"  [{index}/{len(ids)}] {type_name} ID {row_id}")
        try:
            data = fetcher(row_id)
        except MissingData as exc:
            rows.pop(row_id, None)
            set_missing(cache, type_name, row_id, exc.status, str(exc))
            if exc.status == "not_found":
                not_found.append(row_id)
            elif exc.status == "empty":
                empty.append(row_id)
            else:
                empty.append(row_id)
            print(f"    warning: {exc.status}: {exc}")
            continue
        rows[row_id] = data
        clear_missing(cache, type_name, row_id)

    current_missing = missing_ids(cache, type_name).get(type_name, [])

    meta = {
        "generated_at": datetime.now(timezone.utc).replace(microsecond=0).isoformat(),
        "source": "XIVAPI v2",
        "type": type_name,
        "languages": list(LANGUAGES),
        "requested_ids": ids,
        "skipped_ids": skipped,
        "skipped_missing_ids": skipped_missing,
        "not_found_ids": not_found,
        "empty_ids": empty,
        "missing_ids": current_missing,
        "failed_ids": not_found + empty,
        "count": len(rows),
    }
    write_lua_table(target, rows, meta)
    cache[type_name] = {str(row_id): rows[row_id] for row_id in sorted(rows)}
    print(
        f"  wrote {display_path(target)} "
        f"({len(rows)} rows, {len(skipped)} cached, {len(skipped_missing)} known missing, "
        f"{len(not_found)} not found, {len(empty)} empty)"
    )


def display_path(path: Path) -> str:
    try:
        return str(path.relative_to(ROOT))
    except ValueError:
        return str(path)


def search(type_name: str, query: str, language: str, limit: int) -> None:
    if type_name not in SEARCHABLE_TYPES:
        raise ExportError(f"{type_name} is exportable by ID, but not searchable by text")
    languages = LANGUAGES if language == "all" else (language,)
    config = EXPORTERS[type_name]
    search_field = config["search_field"]
    query_expr = f'{search_field}~"{query}"'

    results_by_id: dict[int, tuple[str, dict[str, Any]]] = {}
    for lang in languages:
        params = {
            "sheets": config["sheet"],
            "query": query_expr,
            "fields": config["search_fields"],
            "language": lang,
            "limit": limit,
        }
        data = http_json("/search", params)
        for result in data.get("results", []) if data else []:
            row_id = result.get("row_id")
            if isinstance(row_id, int) and row_id not in results_by_id:
                results_by_id[row_id] = (lang, result)

    results = sorted(results_by_id.values(), key=lambda item: item[1].get("score", 0), reverse=True)

    print(f"Search {type_name} for '{query}' ({language}): {len(results)} result(s)")
    for lang, result in results:
        row_id = result.get("row_id")
        score = result.get("score", 0)
        fields = result.get("fields") or {}
        label = search_label(type_name, fields)
        print(f"  {row_id:<7} lang={lang} score={score:.3f}  {label}")


def search_label(type_name: str, fields: dict[str, Any]) -> str:
    if type_name == "items":
        return str(fields.get("Name") or "")
    if type_name == "bnpc_names":
        return str(fields.get("Singular") or "")
    if type_name in ("territories", "maps"):
        place = fields.get("PlaceName")
        if isinstance(place, dict):
            place_fields = place.get("fields") or {}
            name = place_fields.get("Name") or ""
        else:
            name = ""
        extra = []
        map_ref = fields.get("Map@as(raw)") or fields.get("Map")
        territory_ref = fields.get("TerritoryType@as(raw)") or fields.get("TerritoryType")
        if ref_id(map_ref):
            extra.append(f"map={ref_id(map_ref)}")
        if ref_id(territory_ref):
            extra.append(f"territory={ref_id(territory_ref)}")
        suffix = f" ({', '.join(extra)})" if extra else ""
        return f"{name}{suffix}"
    if type_name == "place_names":
        return str(fields.get("Name") or "")
    if type_name == "bnpc_bases":
        rank = fields.get("Rank") or 0
        scale = fields.get("Scale") or 0
        model_chara_id = ref_id(fields.get("ModelChara@as(raw)")) or 0
        return f"rank={rank}, scale={scale}, model_chara_id={model_chara_id}"
    return str(fields)


def print_missing(cache: dict[str, Any], type_name: str | None = None) -> None:
    missing = missing_cache(cache)
    selected = missing_ids(cache, type_name)
    if not selected:
        print("No known missing IDs.")
        return

    for current_type, ids in selected.items():
        print(f"{current_type}: {len(ids)} missing ID(s)")
        type_missing = missing.get(current_type, {})
        for row_id in ids:
            entry = type_missing.get(str(row_id), {})
            status = entry.get("status", "missing")
            checked = entry.get("last_checked_at", "?")
            message = entry.get("message", "")
            print(f"  {row_id:<7} {status:<10} {checked}  {message}")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Export selected XIVAPI v2 rows into data/generated/*.lua",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python tools/export_xivapi_data.py export --items 12628,5496 --bnpc-names 3471 --territories 397
  python tools/export_xivapi_data.py export --items 500-1000 --mobs 1,5,50-80
  python tools/export_xivapi_data.py export --items 12628 --refresh
  python tools/export_xivapi_data.py missing --type item
  python tools/export_xivapi_data.py retry-missing --type item
  python tools/export_xivapi_data.py search item "Glotzaugen-Tränen" --language de
  python tools/export_xivapi_data.py search mob "deepeye" --language all
  python tools/export_xivapi_data.py search territory "Coerthas" --language en
""",
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    export_parser = subparsers.add_parser("export", help="Export IDs into Lua files")
    export_parser.add_argument("--items", default="", help="Item IDs/ranges, e.g. 12628,500-510")
    export_parser.add_argument("--mobs", "--bnpc-names", dest="bnpc_names", default="", help="BNpcName IDs/ranges")
    export_parser.add_argument("--territories", "--zones", dest="territories", default="", help="TerritoryType IDs/ranges")
    export_parser.add_argument("--maps", default="", help="Map IDs/ranges")
    export_parser.add_argument("--place-names", dest="place_names", default="", help="PlaceName IDs/ranges")
    export_parser.add_argument("--bnpc-bases", dest="bnpc_bases", default="", help="BNpcBase IDs/ranges")
    export_parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR, help="Output directory")
    export_parser.add_argument("--replace", action="store_true", help="Replace selected generated files instead of adding to cache")
    export_parser.add_argument("--refresh", action="store_true", help="Refetch requested IDs even if they are already cached")
    export_parser.add_argument("--retry-missing", action="store_true", help="Retry IDs previously marked not_found/empty")

    missing_parser = subparsers.add_parser("missing", help="List IDs previously marked not_found/empty")
    missing_parser.add_argument("--type", default="", help="Optional type filter: item, mob, territory, map, place_name, bnpc_base")
    missing_parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR, help="Output directory")

    retry_parser = subparsers.add_parser("retry-missing", help="Retry IDs previously marked not_found/empty")
    retry_parser.add_argument("--type", default="", help="Optional type filter: item, mob, territory, map, place_name, bnpc_base")
    retry_parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR, help="Output directory")

    search_parser = subparsers.add_parser("search", help="Search IDs by text")
    search_parser.add_argument("type", help="item, mob, territory, map, place_name")
    search_parser.add_argument("query", help="Search text")
    search_parser.add_argument("--language", default="de", choices=(*LANGUAGES, "all"), help="Search language")
    search_parser.add_argument("--limit", type=int, default=10, help="Maximum result count")

    return parser


def run_export(args: argparse.Namespace) -> None:
    requested = {
        "items": parse_id_spec(args.items),
        "bnpc_names": parse_id_spec(args.bnpc_names),
        "territories": parse_id_spec(args.territories),
        "maps": parse_id_spec(args.maps),
        "place_names": parse_id_spec(args.place_names),
        "bnpc_bases": parse_id_spec(args.bnpc_bases),
    }

    selected = {type_name: ids for type_name, ids in requested.items() if ids}
    if not selected:
        raise ExportError("No IDs provided. Use e.g. --items 12628 or --mobs 3471.")

    cache = load_cache(args.output_dir)

    for type_name, ids in selected.items():
        export_type(
            type_name,
            ids,
            args.output_dir,
            cache,
            replace=args.replace,
            refresh=args.refresh,
            retry_missing=args.retry_missing,
        )

    save_cache(args.output_dir, cache)


def run_missing(args: argparse.Namespace) -> None:
    cache = load_cache(args.output_dir)
    type_name = normalize_type(args.type) if args.type else None
    print_missing(cache, type_name)


def run_retry_missing(args: argparse.Namespace) -> None:
    cache = load_cache(args.output_dir)
    type_name = normalize_type(args.type) if args.type else None
    selected = missing_ids(cache, type_name)
    if not selected:
        print("No known missing IDs to retry.")
        return

    for current_type, ids in selected.items():
        export_type(
            current_type,
            ids,
            args.output_dir,
            cache,
            replace=False,
            refresh=False,
            retry_missing=True,
        )

    save_cache(args.output_dir, cache)


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    try:
        if args.command == "export":
            run_export(args)
        elif args.command == "missing":
            run_missing(args)
        elif args.command == "retry-missing":
            run_retry_missing(args)
        elif args.command == "search":
            search(normalize_type(args.type), args.query, args.language, args.limit)
        else:
            parser.error(f"Unknown command {args.command}")
    except (ExportError, ValueError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
